version: "3.8"

services:
  db:
    ports:
      - ${DB_EXTERNAL_PORT:-5432}:5432

  api:
    build:
      context: ../../api
      dockerfile: docker/Dockerfile
      target: debug
    image: api-debug
    volumes:
      - ../../api:/app
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: dev-secret

  frontend:
    build:
      context: ../../frontend
      dockerfile: docker/Dockerfile
      target: debug
    image: frontend-debug
    ports:
      - 3000:3000
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    stdin_open: true
    environment:
      REACT_APP_BASE_API_URL: http://localhost:8000/api/v1/jobs
